export const SET_AUTHORIZED = "SET_AUTHORIZED";
export const SET_UNAUTHORIZED = "SET_UNAUTHORIZED";
export const SET_USER_DATA = "SET_USER_DATA";
export const UNSET_USER_DATA = "UNSET_USER_DATA";
export const SET_DEVICE_DATA = "SET_DEVICE_DATA";
export const UPDATE_DEVICE_DATA = "UPDATE_DEVICE_DATA";
export const UNSET_DEVICE_DATA = "UNSET_DEVICE_DATA";